### ISSUE TITLE
Two CGMiner screen processes

### ISSUE THREAD

**Issue by jedimstr** [starlilyth/Linux-PoolManager#44]
I get two CGMiner screen processes when I startup my SMOS/Linux-PoolManager miner.

One is labelled `cgminer` and is the original startup from `/opt/bamt/common.pl`.
The second is labelled `PM-miner` which I assume is the new one provided by Linux-PoolManager.  

Both startup after boot with the original `cgminer` process taking the GPUs and `PM-miner` waiting.  When I let `cgminer` stay, it can be controlled by the old command-line commands from BAMT: `mine start` `mine stop` `mine restart`, but restarting from the Web Interface doesn't work anymore.  If I let `PM-miner` live and kill the other, and then restart cgminer from within the screen, it picks up the GPUs and the WebUI can now control cgminer restarts. 

So a few questions:
1. Where is the safest place to disable the original `cgminer` screen startup?  Do I comment out the line in common.pl (or do you even use common.pl anymore)? Or is it safer to disable elsewhere (whatever is calling the miner to startup or setting it up like in `/etc/init.d/mine`?
2. With the `mine` command disabled, is there an equivalent for use with the `PM-miner` screen process at the shell promt?  
3. I remember seeing an option in miner configuration in previous versions to use the BAMT controls for mine start stop.  I assume they went away when this `PM-miner` screen process was introduced.  Why did you go this route?

You may need to add to your install script something to disable the screen process defined in common.pl and automatically started on boot or others may end up with two cgminer processes.

**Comment by starlilyth** [comment]
I no longer have a BAMT rig to check, but I think you can edit /etc/bamt/bamt.conf and disable mine on boot there.

**Comment by Vap0rz** [comment]
Star is correct, you can find it in your bamt.conf file-
Just put a zero behind the cgminer entry under each GPU:

gpu0:
  # remove disabled: or set it to 0 to actually use this card..
  cgminer: 1   <---- Change this to 0 on all of your GPU entries

Hope that helps..

**Comment by Vap0rz** [comment]
Any thoughts on setting this up for a Raspberry Pi miner and or Gridseed hardware? I like the simple straight forward interface!

**Comment by starlilyth** [comment]
Thanks Vap0rz. I will go ahead and close this issue. 
I dont have a Pi or Gridseed to test on, but as long as the requirements are met it should work. 

Lily

**Comment by Vap0rz** [comment]
Hi Star-
So I am a bit new to GIT - hopefully I didn't screw anything up on the site
there!
First, thank you for your work- it's being used in several places now- PIMP
is the big one that comes to mind. Nice job.
Anyway, as far as the gridseed ASIC PI miners go, i found out there are
several issues so it's most likely not worth your time but here are a few
issues I noticed if your curious:

The api call for cgminer (or sgminer) has a different ID for checking
cpucount or gpucount, for ASICS its asccount. So along with that, calls to
specific devices are asc1 versus gpu1.  Obviously ASIC devices won't have
temps or fans speeds and it's complicated by sgminer uses xintensity along
with regular intensity that messes up standard GPU calls.
Also the Pi's are very small foot print, tiny CPU's. I tried tossing it on
a few but when the status.pl runs it spikes the PI CPU up to 100%.
Typically PI will use lighttpd instead of apache2 as it was designed for
fast, low overhead integrated devices. Of course lighttpd configs are not
equal to apache2 so thats even more of a bummer.

As crypto moves forward, scrypt-j and scrypt asics are becoming more
popular. If this is something your thinking about working on, please let me
know. I can supply some API ASIC dumps, or even open a live one up to an
internet address for you to play with. Seems like a lot of work though,
just thought I'd offer the help ..
Cheers

On Wed, Apr 9, 2014 at 4:11 PM, Lily Star notifications@github.com wrote:

> Closed #44 https://github.com/starlilyth/Linux-PoolManager/issues/44.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/starlilyth/Linux-PoolManager/issues/44
> .

## 

You have been eaten by a grue...

**Comment by starlilyth** [comment]
No problem :) I am starting a new Issue for this thread however, please follow on there.
